### ISSUE TITLE
common legend for multiple figures

### ISSUE THREAD

**Issue by SONG-MAN** [LKremer/ggpointdensity#22]
Thank you very much for providing such useful codes. I plotted several figures, but the legend of each picture is different. 
I want to combine multiple figures with only one legend used.
I am wondering if I could change the "adjust" parameter of each figure to make them have the same legends.
Or there are other ways to solve this.

Thank you for your attention.

**Comment by LKremer** [comment]
Hi @SONG-MAN,
thanks for the question.

I can think of two solutions to your problem: Either you use faceting, or you manually set the legend limits.
I will give you a quick example:

```R
library(ggplot2)
library(dplyr)
library(viridis)
library(ggpointdensity)

df1 <- tibble(x = rnorm(7000, sd = 1),
              y = rnorm(7000, sd = 10),
              group = "foo")

df2 <- tibble(x = rnorm(3000, mean = 1, sd = .5),
              y = rnorm(3000, mean = 7, sd = 5),
              group = "bar")
```

If I just plot `df1` and `df2` separately, they will have different legends of course. To fix it, the easiest solution is to merge `df1` and `df2` into one data frame (or tibble) and then use `facet_wrap()` or `facet_grid()`:

```R
all_data <- bind_rows(df1, df2)

ggplot(data = all_data, mapping = aes(x = x, y = y)) +
  geom_pointdensity() +
  scale_color_viridis() +
  facet_wrap(~group)
```
![image](https://github.com/LKremer/ggpointdensity/assets/15158974/a88bdd45-6e0c-4ffd-9078-1f9a1586b054)
This way, you will have a separate plot panel for each of the two sub-data sets, but they will share one legend. Of course, your merged data frame needs a grouping column, so that you can still distinguish the two data sets.

Another option is to produce two separate plots where you manually set the limits of the color scale, like this:
```R
ggplot(data = df1, mapping = aes(x = x, y = y)) +
  geom_pointdensity() +
  scale_color_viridis(limits = c(NA, 420))
```
![image](https://github.com/LKremer/ggpointdensity/assets/15158974/b31a0892-65be-4797-af22-cb9aff5d6545)


```R
ggplot(data = df2, mapping = aes(x = x, y = y)) +
  geom_pointdensity() +
  scale_color_viridis(limits = c(NA, 420))
```
![image](https://github.com/LKremer/ggpointdensity/assets/15158974/7663da51-3c71-4f49-a71b-2b565bb3e3b9)

I hope this answers your question!

**Comment by SONG-MAN** [comment]
Thank you very much for providing the solution and the example. It works great!

**Comment by LKremer** [comment]
Nice!
